(setq confirm-kill-emacs #'yes-or-no-p)
(electric-pair-mode t)
(add-hook 'prog-mode-hook #'show-paren-mode)
(column-number-mode t)
(global-auto-revert-mode t)
(delete-selection-mode t)
(setq inhibit-startup-message t)
(setq auto-save-default nil)
(setq make-backup-files nil)
(global-display-line-numbers-mode 1)
(when (display-graphic-p)
  (toggle-scroll-bar -1)
  (menu-bar-mode -1)
  (tool-bar-mode -1))

(provide 'basic)
